version: "3.9"

services:
  telegram-bot:
    build:
      context: .
    container_name: telegram-bot
    restart: unless-stopped
    volumes:
      - .:/app
    working_dir: /app
    command: python tg_bot.py
